core/urls.py
from django.contrib import admin
from django.urls import include, path
from playlist.views import playlists

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", playlists, name="home"),
    #path('movies/', include('movies.urls')),
    path('playlists/', include('playlist.urls')),
    path('users/', include('users.urls')),
]

movies/urls.py
from django.urls import path

app_name = 'movies'
urlpatterns = [
]

playlist/urls.py
from django.urls import path
from .views import playlists, show, new, search, new_movie_playlist, delete_from_playlist, delete_playlist, compartilhar

app_name = 'playlists'
urlpatterns = [
    path('', playlists, name="list"),
    path('show/<int:pk>', show, name="show"),
    path('new', new, name='new'),
    path('search/<int:pk>', search, name='search'),
    path('add/<int:pk>', new_movie_playlist, name="addmovie"),
    path('delete/<int:playlist>', delete_from_playlist, name="delete_from_pl"),
    path('deleteplaylist', delete_playlist, name="delete_pl"),
    path('compartilhar', compartilhar, name="compartilhar")
]

users/urls.py
from django.urls import include, path
from .views import signup, logout_user, Login

app_name = "users"
urlpatterns = [
    path("signup", signup, name="signup"),
    path("logout", logout_user, name="logout"),
    path("login", Login.as_view(), name="login")
]

movies/models.py
from django.db import models


class Movie(models.Model):
    idmovie = models.IntegerField()
    playlist = models.ForeignKey(
        "playlist.Playlist", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.idmovie)

playlist/models.py
from django.db import models
from django.contrib.auth.models import User


class Playlist(models.Model):
    name = models.CharField(max_length=50, default="no name")
    user = models.ForeignKey(User, on_delete="CASCADE")

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.


class Registered(models.Model):
    chat_id = models.CharField(max_length=50)

    def __str__(self):
        return self.chat_id

playlist/forms.py
from django import forms
from .models import Playlist


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['name']

movies/views.py
from django.shortcuts import render
from .models import Movie

import requests

key = 'api_key=0c6d96dc4c081f6c309a563acbcbd996'
base = 'http://api.tmdb.org/3/'
# Create your views here.


def show(request, id):


http: // api.tmdb.org/3/movie/63441?api_key = 0c6d96dc4c081f6c309a563acbcbd996

playlist/views.py
from django.contrib.auth.decorators import login_required
from .forms import PlaylistForm
from movies.models import Movie
from .models import Playlist
from django.shortcuts import render, redirect, get_object_or_404
import requests
from .share_bot import send_to_all
import datetime
from django.contrib import messages

# Create your views here.

SITE_URL = 'http://127.0.0.1:8000/'


class Details:
    title = None
    vote_average = None
    runtime = None
    id_movie = None
    poster_path = None
    release_date = None
    genre = []
    id_db = None
    imdb = None


key = 'api_key=0c6d96dc4c081f6c309a563acbcbd996'
base = 'http://api.tmdb.org/3/'

'''
retorna as playlists do usuário (logado)
'''


@login_required
def playlists(request):
    playlists = Playlist.objects.filter(user_id=request.user.pk)
    return render(request, "playlist/playlists.html", {"playlists": playlists})


def show(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk)
    objs = Movie.objects.filter(playlist_id=pk)
    movies = []
    for m in objs:
        url = base+'movie/'+str(m.idmovie)+'?'+key
        r = requests.get(url).json()
        detail = get_details(r, m)
        movies.append(detail)
        detail = None
    return render(request, 'playlist/movies_playlist.html', {"movies": movies, "playlist": playlist})


@login_required
def new(request):
    if request.method == 'GET':
        form = PlaylistForm()
        return render(request, 'playlist/new.html', {'form': form})
    else:
        form = PlaylistForm(request.POST)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            messages.success(request, 'Playlist criada!')
        else:
            messages.error(request, 'Erro ao criar playlist')
    return redirect("playlists:list")


@login_required
def search(request, pk):
    playlist = get_object_or_404(Playlist, pk=pk, user_id=request.user.pk)

    if request.method == 'GET':
        return render(request, "playlist/search_movie.html", {"playlist": playlist})
    search_movie = request.POST.get('busca', None)
    if search_movie is "":
        return render(request, 'playlist/search_movie.html', {"playlist": playlist})
    else:
        movie = search_movie.replace(' ', '+')
        url = base+'search/movie?'+key+'&query='+movie
        r = requests.get(url).json()
        movies = []
        for i in r['results']:
            movies.append(i)
        return render(request, "playlist/search_movie.html", {"busca": movies, "playlist": playlist})


@login_required
def new_movie_playlist(request, pk):
    if request.method == 'GET':
        return redirect("playlists:search", pk=pk)
    else:
        playlist = get_object_or_404(Playlist, pk=pk, user_id=request.user.pk)
        movies_add = request.POST.getlist('movies[]')
        for m in movies_add:
            movie = Movie()
            movie.idmovie = m
            movie.playlist = playlist
            movie.save()
    return redirect("playlists:list")


@login_required
def delete_from_playlist(request, playlist):
    try:
        id_movie = request.POST.get("movie")
        movie = get_object_or_404(Movie, pk=id_movie)
        playlist_obj = get_object_or_404(Playlist, pk=movie.playlist_id)
        if(request.user == playlist_obj.user):
            movie.delete()
            messages.success(request, 'Filme removido!')
        return redirect("playlists:show", pk=playlist)
    except:
        messages.success(request, 'Erro ao remover filme!')
    return redirect("playlists:show", pk=playlist)


@login_required
def delete_playlist(request):
    try:
        id_playlist = request.POST.get("playlist")
        playlist = get_object_or_404(
            Playlist, pk=id_playlist, user_id=request.user.pk)
        playlist.delete()
        messages.success(request, 'Playlist Removida!')
        return redirect("playlists:list")
    except:
        messages.error(request, 'Erro ao remover playlist!')
        return redirect("playlists:list")


@login_required
def compartilhar(request):

    try:
        pk = request.POST.get("share")
        playlist_url = SITE_URL+'playlists/show/'+pk
        send_to_all(playlist_url, request.user.username)
        messages.success(request, 'Playlist compartilhada!')
        return redirect("playlists:list")
    except:
        messages.error(request, 'Erro ao compartilhar playlist!')
        return redirect("playlists:list")


def get_details(json, m):
    detail = Details()
    detail.title = json['title']
    detail.vote_average = json['vote_average']
    detail.runtime = json['runtime']
    detail.idmovie = json['id']
    detail.poster_path = json['poster_path']
    detail.release_date = json['release_date']
    detail.release_date = datetime.datetime.strptime(
        detail.release_date, "%Y-%m-%d").strftime("%d/%m/%Y")
    detail.id_db = m.id
    detail.imdb = json['imdb_id']
    # for genre in json['genres']:
    #    detail.genre.append(genre['name'])
    genres = json['genres']
    g = [d['name'] for d in genres]
    detail.genre = g
    return detail

users/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('home')


class Login(LoginView):
    form_class = AuthenticationForm
    authentication_form = None
    template_name = 'registration/login.html'
    redirect_authenticated_user = 'home'

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <span style="color: white;"
          >{% if user.is_authenticated %} Olá, {{ user.get_username }}! {% endif %}</span
        >
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'playlists:list' %}"
                >Playlists
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Sair</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Entrar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:signup' %}"
                >Criar conta</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
{% if messages %}
  {% for message in messages %}
    <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
{% endfor %}
{% endif %}
    <main role="main" class="container">
      {% block main %} {% endblock main %}
    </main>
    <script
      type="text/javascript"
      src="{% static 'js/jquery-3.4.1.min.js' %}"
    ></script>

    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.min.js' %}"
    ></script>
  </body>
</html>

templates/playlist/movies_playlist.html
{% extends 'base.html' %} {% block main %}

<div class="row mb-2" style="margin: 25px;">
  {% if not movies %}
  <p>Ainda não há filmes cadastrados</p>
  {% endif %} {% for movie in movies %}
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary"
          >{% for genre in movie.genre %} {{ genre }} {% endfor %}</strong
        >
        <h3 class="mb-0">
          <a class="text-dark" target="new_blank" href="https://www.imdb.com/title/{{movie.imdb}}">{{ movie.title }}</a>
        </h3>
        <div class="mb-1 text-muted">{{ movie.runtime }} mins</div>
        <p class="card-text mb-auto">
          Media de votos: {{ movie.vote_average }}<br />
          Data de lançamento: {{ movie.release_date }} <br />
        </p>
        {% if user.is_authenticated %}
        <form action="/playlists/delete/{{ playlist.pk }}" method="POST">
          {% csrf_token %}
          <button
            class="btn-small btn-danger"
            name="movie"
            value="{{ movie.id_db }}"
          >
            Remover da playlist
          </button>
        </form>
        {% endif %}
      </div>
      <img
        class="card-img-right flex-auto d-none d-md-block"
        src="https://image.tmdb.org/t/p/w154/{{ movie.poster_path }}"
        alt="{{ movie.title }}"
      />
    </div>
  </div>
  {% endfor %}
</div>
{% if user.is_authenticated %}
<a
  role="button"
  class="btn btn-primary"
  href="{% url 'playlists:addmovie' playlist.pk %}"
  >Adicionar novo filme</a
>
<a href="{% url 'playlists:list' %}" role="button" class="btn btn-secondary"
  >Voltar</a
>
{% endif %} {% endblock %}

templates/playlist/new.html
{% extends 'base.html' %}

{% block main %}
<div class="card text-center" style="margin: 30px;">
  <div class="card-header">
    Nova playlist
  </div>
  <div class="card-body">
  
 <form method="post"  style="margin: auto;">
  {% csrf_token %}
  <label for="id_name">Nome da playlist:</label>
  <input type="text" name="name" placeholder="Filmes que gostei" required id="id_name" maxlength="50"></p>
  <button class="btn btn-primary" type="submit">Cadastrar</button>
</form>
  </div>
  <div class="card-footer text-muted">
  <a href="{% url 'playlists:list' %}" role="button" class="btn btn-secondary">Cancelar</a>
  </div>
</div>

{% endblock %}

templates/playlist/playlists.html
{% extends 'base.html' %}

<div class="row">

  {% block main %}


<h3 style="text-align: center; margin: 20px;">Playlists</h3>

  {% if not playlists %}
    <h4>Você não possui playlists</h4>
    <br>

    {% else %}
      <div class="row">

    {% for playlist in playlists %}
  <div class="col-sm-6" style="margin-bottom: 20px;">
    <div class="card">
     <div class="card-header" style="text-align: center;">
      <b>{{playlist}}</b>
    </div>
      <div class="card-body d-flex justify-content-center" >
        <form action="/playlists/compartilhar" method="POST">
          {% csrf_token %}
          <button class="btn btn-primary" name="share" value="{{ playlist.pk }}">Compartilhar</button>
        </form>
        <form action="/playlists/deleteplaylist" method="POST" style="margin-left: 10px; margin-right: 10px;">
          {% csrf_token %}
          <button class="btn btn-danger" name="playlist" value="{{ playlist.pk }}">Excluir</button>
        </form>
        <a role="button" class="btn btn-warning" href="{% url 'playlists:show' playlist.pk %}"> Ver playlist</a>
      </div>
    </div>
  </div>





      {% endfor %}
</div>

  {% endif %}

  <a role="button" class="btn btn-primary" href="{% url 'playlists:new' %}">Nova playlist</a>
</div>
{% endblock %}

templates/playlist/search_movie.html
{% extends 'base.html' %} {% block main %}
<div class="card text-center" style="margin: 15px;">
  <div class="card-header">
    Adicionando filmes na playlist {{ playlist.name }}
  </div>
  <div class="card-body">
    <form
      type="post"
      method="post"
      action="/playlists/search/{{ playlist.pk }}"
      style="margin: 0"
    >
      {% csrf_token %}
      <input id="busca" type="text" name="busca" placeholder="Nome do filme" />
      <button class="btn btn-primary" id="search_submit" type="submit">
        Buscar
      </button>
    </form>
  </div>
  <div class="card-footer text-muted">
    <a href="{% url 'playlists:list' %}" role="button" class="btn btn-secondary"
      >Cancelar</a
    >
  </div>
</div>
<div class="row" style="padding-bottom: 20px;">
  <form method="post" action="/playlists/add/{{ playlist.pk }}">
    {% csrf_token %}
    <div class="row mb-2" style="margin: 25px;">
      {% if not busca %}
      <p>Sem resultados</p>
      {% endif %} {% for filme in busca %}

      <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
          <div class="card-body d-flex flex-column align-items-start">
            <h3 class="mb-0">
              <p class="text-dark">
                <input type="checkbox" name="movies[]" value="{{ filme.id }}" />
                <br />
                {{ filme.title }}
              </p>
            </h3>
          </div>
          <img
            class="card-img-right flex-auto d-none d-md-block"
            src="https://image.tmdb.org/t/p/w92/{{ filme.poster_path }}"
            alt="{{ filme.title }}"
          />
        </div>
      </div>

      {% endfor %}
    </div>
    {% if busca %}
    <button class="btn-lg btn-primary" id="search_submit" type="submit">
      Adicionar filmes selecionados
    </button>
    {% endif %}
  </form>
</div>
{% endblock %}